/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/health": {
    /**
     * Health Check
     * @description Health check endpoint
     */
    get: operations["health_check_api_v1_health_get"];
  };
  "/api/v1/meetings": {
    /**
     * List Meetings
     * @description List meetings, optionally filtered by user email
     */
    get: operations["list_meetings_api_v1_meetings_get"];
  };
  "/api/v1/meetings/{meeting_id}": {
    /**
     * Get Meeting
     * @description Get a specific meeting by ID
     */
    get: operations["get_meeting_api_v1_meetings__meeting_id__get"];
  };
  "/api/v1/meetings/{meeting_id}/attendees": {
    /**
     * Get Meeting Attendees
     * @description Get attendees for a specific meeting
     */
    get: operations["get_meeting_attendees_api_v1_meetings__meeting_id__attendees_get"];
  };
  "/api/v1/meetings/join": {
    /**
     * User Join Meeting
     * @description User-facing endpoint to request bot to join a meeting
     */
    post: operations["user_join_meeting_api_v1_meetings_join_post"];
  };
  "/api/v1/meetings/{meeting_id}/leave": {
    /**
     * User Leave Meeting
     * @description User-facing endpoint to request bot to leave a meeting
     */
    post: operations["user_leave_meeting_api_v1_meetings__meeting_id__leave_post"];
  };
  "/api/v1/bot/join": {
    /**
     * Bot Join Meeting
     * @description Bot endpoint to join a meeting and create meeting record
     */
    post: operations["bot_join_meeting_api_v1_bot_join_post"];
  };
  "/api/v1/bot/leave": {
    /**
     * Bot Leave Meeting
     * @description Bot endpoint to leave a meeting and update meeting record
     */
    post: operations["bot_leave_meeting_api_v1_bot_leave_post"];
  };
  "/api/v1/bot/attendees/{meeting_id}": {
    /**
     * Update Attendees
     * @description Update meeting attendees list
     */
    post: operations["update_attendees_api_v1_bot_attendees__meeting_id__post"];
  };
  "/api/v1/ingest/transcript": {
    /**
     * Ingest Transcript Segment
     * @description HTTP endpoint for transcript segment ingestion (from STT worker)
     */
    post: operations["ingest_transcript_segment_api_v1_ingest_transcript_post"];
  };
  "/api/v1/ingest/status/{meeting_id}": {
    /**
     * Get Ingestion Status
     * @description Get current ingestion status for a meeting
     */
    get: operations["get_ingestion_status_api_v1_ingest_status__meeting_id__get"];
  };
  "/api/v1/meetings/{meeting_id}/transcript": {
    /**
     * Get Meeting Transcript
     * @description Get transcript segments for a meeting with pagination and filtering
     */
    get: operations["get_meeting_transcript_api_v1_meetings__meeting_id__transcript_get"];
  };
  "/api/v1/meetings/{meeting_id}/transcript/stats": {
    /**
     * Get Transcript Stats
     * @description Get transcript statistics for a meeting
     */
    get: operations["get_transcript_stats_api_v1_meetings__meeting_id__transcript_stats_get"];
  };
  "/api/v1/meetings/{meeting_id}/transcript/search": {
    /**
     * Search Transcript
     * @description Search transcript content using full-text search
     */
    get: operations["search_transcript_api_v1_meetings__meeting_id__transcript_search_get"];
  };
  "/api/v1/meetings/{meeting_id}/summary": {
    /**
     * Get Meeting Summaries
     * @description Get all summaries for a meeting
     */
    get: operations["get_meeting_summaries_api_v1_meetings__meeting_id__summary_get"];
  };
  "/api/v1/meetings/{meeting_id}/summary/{summary_type}": {
    /**
     * Get Meeting Summary By Type
     * @description Get the latest summary of a specific type for a meeting
     */
    get: operations["get_meeting_summary_by_type_api_v1_meetings__meeting_id__summary__summary_type__get"];
  };
  "/api/v1/meetings/{meeting_id}/summary:generate": {
    /**
     * Generate Summary
     * @description Generate a new summary for a meeting
     */
    post: operations["generate_summary_api_v1_meetings__meeting_id__summary_generate_post"];
  };
  "/api/v1/chat/rag": {
    /**
     * Chat With Meeting
     * @description Chat with meeting content using RAG (Retrieval Augmented Generation)
     */
    post: operations["chat_with_meeting_api_v1_chat_rag_post"];
  };
  "/": {
    /** Root */
    get: operations["root__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AttendeeResponse */
    AttendeeResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string | null;
      /** Name */
      name: string | null;
      /** Is Host */
      is_host: boolean;
      /** Joined At */
      joined_at: string | null;
      /** Left At */
      left_at: string | null;
    };
    /** Body_update_attendees_api_v1_bot_attendees__meeting_id__post */
    Body_update_attendees_api_v1_bot_attendees__meeting_id__post: {
      /** Attendees */
      attendees: unknown[];
    };
    /** ChatRequest */
    ChatRequest: {
      /** Question */
      question: string;
      /**
       * Context Window
       * @default 5
       */
      context_window?: number | null;
    };
    /** ChatResponse */
    ChatResponse: {
      /** Answer */
      answer: string;
      /** Sources */
      sources: Record<string, never>[];
      /**
       * Meeting Id
       * Format: uuid
       */
      meeting_id: string;
    };
    /** GenerateSummaryRequest */
    GenerateSummaryRequest: {
      /**
       * Summary Type
       * @default narrative
       */
      summary_type?: string;
      /**
       * Force Regenerate
       * @default false
       */
      force_regenerate?: boolean;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** JoinMeetingRequest */
    JoinMeetingRequest: {
      /** Webex Meeting Id */
      webex_meeting_id: string;
      /** Title */
      title?: string | null;
      /** Host Email */
      host_email?: string | null;
    };
    /** JoinMeetingResponse */
    JoinMeetingResponse: {
      /**
       * Meeting Id
       * Format: uuid
       */
      meeting_id: string;
      /** Status */
      status: string;
      /** Message */
      message: string;
    };
    /** LeaveMeetingRequest */
    LeaveMeetingRequest: {
      /**
       * Meeting Id
       * Format: uuid
       */
      meeting_id: string;
    };
    /** LeaveMeetingResponse */
    LeaveMeetingResponse: {
      /**
       * Meeting Id
       * Format: uuid
       */
      meeting_id: string;
      /** Status */
      status: string;
      /** Message */
      message: string;
    };
    /** MeetingResponse */
    MeetingResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Webex Meeting Id */
      webex_meeting_id: string;
      /** Title */
      title: string | null;
      /** Host Email */
      host_email: string | null;
      /**
       * Start Time
       * Format: date-time
       */
      start_time: string;
      /** End Time */
      end_time: string | null;
      /** Status */
      status: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** SummaryResponse */
    SummaryResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Summary Type */
      summary_type: string;
      /** Content */
      content: string;
      /** Version */
      version: number;
      /** Generated By */
      generated_by: string;
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
    };
    /** TranscriptSegmentResponse */
    TranscriptSegmentResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Speaker Name */
      speaker_name: string | null;
      /** Speaker Email */
      speaker_email: string | null;
      /** Text */
      text: string;
      /** Start Ms */
      start_ms: number;
      /** End Ms */
      end_ms: number;
      /** Confidence */
      confidence: number | null;
      /** Language */
      language: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** UserJoinMeetingRequest */
    UserJoinMeetingRequest: {
      /** Webex Meeting Id */
      webex_meeting_id: string;
      /** Title */
      title?: string | null;
      /** Host Email */
      host_email?: string | null;
    };
    /** UserJoinMeetingResponse */
    UserJoinMeetingResponse: {
      /**
       * Meeting Id
       * Format: uuid
       */
      meeting_id: string;
      /** Status */
      status: string;
      /** Message */
      message: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Health Check
   * @description Health check endpoint
   */
  health_check_api_v1_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * List Meetings
   * @description List meetings, optionally filtered by user email
   */
  list_meetings_api_v1_meetings_get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
        user_email?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MeetingResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Meeting
   * @description Get a specific meeting by ID
   */
  get_meeting_api_v1_meetings__meeting_id__get: {
    parameters: {
      path: {
        meeting_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MeetingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Meeting Attendees
   * @description Get attendees for a specific meeting
   */
  get_meeting_attendees_api_v1_meetings__meeting_id__attendees_get: {
    parameters: {
      path: {
        meeting_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AttendeeResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * User Join Meeting
   * @description User-facing endpoint to request bot to join a meeting
   */
  user_join_meeting_api_v1_meetings_join_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserJoinMeetingRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserJoinMeetingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * User Leave Meeting
   * @description User-facing endpoint to request bot to leave a meeting
   */
  user_leave_meeting_api_v1_meetings__meeting_id__leave_post: {
    parameters: {
      path: {
        meeting_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Bot Join Meeting
   * @description Bot endpoint to join a meeting and create meeting record
   */
  bot_join_meeting_api_v1_bot_join_post: {
    parameters: {
      header: {
        authorization: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinMeetingRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["JoinMeetingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Bot Leave Meeting
   * @description Bot endpoint to leave a meeting and update meeting record
   */
  bot_leave_meeting_api_v1_bot_leave_post: {
    parameters: {
      header: {
        authorization: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeaveMeetingRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LeaveMeetingResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update Attendees
   * @description Update meeting attendees list
   */
  update_attendees_api_v1_bot_attendees__meeting_id__post: {
    parameters: {
      header: {
        authorization: string;
      };
      path: {
        meeting_id: string;
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_update_attendees_api_v1_bot_attendees__meeting_id__post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Ingest Transcript Segment
   * @description HTTP endpoint for transcript segment ingestion (from STT worker)
   */
  ingest_transcript_segment_api_v1_ingest_transcript_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /**
   * Get Ingestion Status
   * @description Get current ingestion status for a meeting
   */
  get_ingestion_status_api_v1_ingest_status__meeting_id__get: {
    parameters: {
      path: {
        meeting_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Meeting Transcript
   * @description Get transcript segments for a meeting with pagination and filtering
   */
  get_meeting_transcript_api_v1_meetings__meeting_id__transcript_get: {
    parameters: {
      query?: {
        skip?: number;
        limit?: number;
        start_time_ms?: number | null;
        end_time_ms?: number | null;
        speaker_email?: string | null;
      };
      path: {
        meeting_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TranscriptSegmentResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Transcript Stats
   * @description Get transcript statistics for a meeting
   */
  get_transcript_stats_api_v1_meetings__meeting_id__transcript_stats_get: {
    parameters: {
      path: {
        meeting_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Search Transcript
   * @description Search transcript content using full-text search
   */
  search_transcript_api_v1_meetings__meeting_id__transcript_search_get: {
    parameters: {
      query: {
        /** @description Search query */
        q: string;
        skip?: number;
        limit?: number;
      };
      path: {
        meeting_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Meeting Summaries
   * @description Get all summaries for a meeting
   */
  get_meeting_summaries_api_v1_meetings__meeting_id__summary_get: {
    parameters: {
      path: {
        meeting_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SummaryResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Meeting Summary By Type
   * @description Get the latest summary of a specific type for a meeting
   */
  get_meeting_summary_by_type_api_v1_meetings__meeting_id__summary__summary_type__get: {
    parameters: {
      path: {
        meeting_id: string;
        summary_type: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SummaryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate Summary
   * @description Generate a new summary for a meeting
   */
  generate_summary_api_v1_meetings__meeting_id__summary_generate_post: {
    parameters: {
      path: {
        meeting_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateSummaryRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Chat With Meeting
   * @description Chat with meeting content using RAG (Retrieval Augmented Generation)
   */
  chat_with_meeting_api_v1_chat_rag_post: {
    parameters: {
      query: {
        meeting_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChatRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ChatResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Root */
  root__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
