"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2024-08-16 15:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector
import uuid


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    
    # Create meetings table
    op.create_table('meetings',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid.uuid4),
        sa.Column('webex_meeting_id', sa.String(length=255), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=True),
        sa.Column('host_email', sa.String(length=255), nullable=True),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meeting_webex_id', 'meetings', ['webex_meeting_id'], unique=True)
    op.create_index('idx_meeting_status_start', 'meetings', ['status', 'start_time'], unique=False)
    
    # Create attendees table
    op.create_table('attendees',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid.uuid4),
        sa.Column('meeting_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('webex_user_id', sa.String(length=255), nullable=True),
        sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_host', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attendee_meeting_id', 'attendees', ['meeting_id'], unique=False)
    op.create_index('idx_attendee_email', 'attendees', ['email'], unique=False)
    op.create_index('idx_attendee_meeting_email', 'attendees', ['meeting_id', 'email'], unique=False)
    
    # Create transcript_segments table
    op.create_table('transcript_segments',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid.uuid4),
        sa.Column('meeting_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('speaker_name', sa.String(length=255), nullable=True),
        sa.Column('speaker_email', sa.String(length=255), nullable=True),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('start_ms', sa.Integer(), nullable=False),
        sa.Column('end_ms', sa.Integer(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('language', sa.String(length=10), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transcript_meeting_id', 'transcript_segments', ['meeting_id'], unique=False)
    op.create_index('idx_transcript_meeting_time', 'transcript_segments', ['meeting_id', 'start_ms'], unique=False)
    op.create_index('idx_transcript_speaker', 'transcript_segments', ['speaker_email'], unique=False)
    
    # Create summaries table
    op.create_table('summaries',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid.uuid4),
        sa.Column('meeting_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('summary_type', sa.String(length=50), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=True),
        sa.Column('generated_by', sa.String(length=50), nullable=False),
        sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_summary_meeting_id', 'summaries', ['meeting_id'], unique=False)
    op.create_index('idx_summary_meeting_type', 'summaries', ['meeting_id', 'summary_type'], unique=False)
    
    # Create doc_chunks table
    op.create_table('doc_chunks',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid.uuid4),
        sa.Column('meeting_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('chunk_type', sa.String(length=50), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('start_ms', sa.Integer(), nullable=True),
        sa.Column('end_ms', sa.Integer(), nullable=True),
        sa.Column('embedding', Vector(1536), nullable=True),
        sa.Column('chunk_metadata', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_chunk_meeting_id', 'doc_chunks', ['meeting_id'], unique=False)
    op.create_index('idx_doc_chunk_type', 'doc_chunks', ['chunk_type'], unique=False)
    op.create_index('idx_doc_chunk_meeting_time', 'doc_chunks', ['meeting_id', 'start_ms'], unique=False)
    
    # Create vector index
    op.execute("CREATE INDEX idx_doc_chunk_embedding ON doc_chunks USING ivfflat (embedding) WITH (lists = 100)")
    
    # Create webhook_events table
    op.create_table('webhook_events',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid.uuid4),
        sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('webex_meeting_id', sa.String(length=255), nullable=True),
        sa.Column('payload', sa.Text(), nullable=False),
        sa.Column('processed', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_event_type', 'webhook_events', ['event_type'], unique=False)
    op.create_index('idx_webhook_meeting_id', 'webhook_events', ['webex_meeting_id'], unique=False)
    op.create_index('idx_webhook_processed', 'webhook_events', ['processed'], unique=False)
    
    # Create job_runs table
    op.create_table('job_runs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, default=uuid.uuid4),
        sa.Column('job_type', sa.String(length=50), nullable=False),
        sa.Column('meeting_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('input_data', sa.Text(), nullable=True),
        sa.Column('output_data', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_run_type', 'job_runs', ['job_type'], unique=False)
    op.create_index('idx_job_run_status', 'job_runs', ['status'], unique=False)
    op.create_index('idx_job_run_meeting', 'job_runs', ['meeting_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_runs')
    op.drop_table('webhook_events')
    op.drop_table('doc_chunks')
    op.drop_table('summaries')
    op.drop_table('transcript_segments')
    op.drop_table('attendees')
    op.drop_table('meetings')
    # ### end Alembic commands ###
